version: "3.8"

services:
  ssh-agent:
    build:
      context: ssh
      dockerfile: Dockerfile
    environment:
      - SSH_AUTH_SOCK=/ssh-agent/agent.sock
      - SSH_KEY_PATH=/app/id_ed25519
    volumes:
      - ssh-agent:/ssh-agent
      - ./keys/id_ed25519:/app/id_ed25519

  maestro:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SSH_AUTH_SOCK=/ssh-agent/agent.sock
    volumes:
      - ssh-agent:/ssh-agent
      - ./.env:/app/.env
      - ./servers.yaml:/app/servers.yaml

volumes:
  ssh-agent:
